### ISSUE TITLE
Subject casting to str from gettext_lazy should be done in send

### ISSUE THREAD

**Issue by seik** [marcosgabarda/django-snitch#10]
The casting to str in this line: https://github.com/marcosgabarda/django-snitch/blob/master/snitch/emails.py#L50 makes really difficult to extend translation behavior when sending an email.

IMO this casting should be done in the sending method and after activating the translation, so that line in the `__init__` should be: 

`self.subject = self.default_subject if subject is None else subject`

Notice the lack of `%s`. This way the translation is not forced until later on, when its actually needed.

And then do the casting to str here: https://github.com/marcosgabarda/django-snitch/blob/master/snitch/emails.py#L112

**Comment by systemallica** [comment]
Fixed here: https://github.com/marcosgabarda/django-snitch/pull/12

However I fail to see why we need to cast at all(?), as the subject is a string since the beginning `subject: Optional[str] = None,`

**Comment by seik** [comment]
Using a `gettext_lazy` means the translation is not done until a string representation is needed, ie: a print, sending de mail, concatenating that text with another text...

Not forcing a translation at initialization opens the possibility to force it when needed in the rest of the lifecycle of the object.

My use case for this is being able to do this (pseudo-code):

```
activate_translation()
use_subject()
deactivate_translation()
```
